routes/web.php
<?php

use App\Http\Controllers\customer\RobotController;
use App\Http\Controllers\Dev\MutationController as DevMutationController;
use App\Http\Controllers\Dev\UserController as DevUserController;
use App\Http\Controllers\Dev\BankController as DevBankController;
use App\Http\Controllers\Dev\LevelController as DevLevelController;
use App\Http\Controllers\Dev\RobotController as DevRobotController;
use App\Http\Controllers\Dev\KursController as DevKursController;
use App\Http\Controllers\Dev\ContactController as DevContactController;
use App\Http\Controllers\Dev\TopupController as DevTopupController;
use App\Http\Controllers\Dev\MemberBankController as DevMemberBankController;
use App\Http\Controllers\Dev\MemberController as DevMemberController;
use App\Http\Controllers\Dev\AkunMT5Controller as DevAkunMT5Controller;
use App\Http\Controllers\Dev\WithdrawController as DevWithdrawController;
use App\Http\Controllers\Dev\ActivationaccountController as DevActivationaccountController;
use App\Http\Controllers\Dev\versionapp\VersionController as DevVersionController;
use App\Http\Controllers\Dev\BypassController as DevBypassController;
use App\Http\Controllers\Dev\NetworkController as DevNetworkController;
use App\Http\Controllers\Dev\KeuntunganController as DevKeuntunganController;
//Customer
use App\Http\Controllers\Customer\robot\RobotController as CustomerRobotController;
use App\Http\Controllers\Customer\robot\BeliRobotController as CustomerBeliRobotController;
use App\Http\Controllers\Customer\profile\ProfileController as CustomerProfileController;

//cashier
use App\Http\Controllers\Cashier\masterdata\UserController as CashierUserController;
use App\Http\Controllers\Cashier\topup\TopupController as CashierTopupController;
use App\Http\Controllers\Cashier\WithdrawController as CashierWithdrawController;
use App\Http\Controllers\Cashier\keuntungan\KeuntunganController as CashierKeuntunganController;
use App\Http\Controllers\Cashier\manajemenuser\AkunMT5Controller as CashierAkunMT5Controller;
use App\Http\Controllers\Cashier\ActivationaccountController as CashierActivationaccountController;
use App\Http\Controllers\Cashier\TopupController as CashierTopup2Controller;
use App\Http\Controllers\Cashier\mutasi\MutasiController as CashierMutasiController;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('landingpage.maintenance');
});

Route::get('/test', function () {
    return view('page.dashboard.index');
});
// Route::get('/', function () {
//     return view('auth.login');
// })->middleware(['guest']);


Route::get('/csrf', function () {
    return csrf_token();
});


Route::get('/coomingsoon', function () {
    return view('coomingsoon');
})->name('cooming');

Route::get('/home', function () {
    Session::put('menu', 'home');
    return redirect('/dashboard/home');
});

Route::webhooks('webhook-moota-url');

Route::name('dashboard.')->prefix('dashboard')->middleware(['auth'])->group(function () {
    Route::get('/home', function () {
        return view('page.dashboard.index');
    });
    Route::name('dev.')->prefix('dev')->middleware(['role:Super Admin'])->group(function () {
        //mutasi
        Route::get('/mutasi', [DevMutationController::class, 'index'])->name('mutasi.index');
        Route::post('/mutasi/cek', [DevMutationController::class, 'find'])->name('mutasi.index.find');
        Route::post('/mutasi/usercek', [DevMutationController::class, 'usercek'])->name('mutasi.index.usercek');
        Route::post('/mutasi/store', [DevMutationController::class, 'store'])->name('mutasi.index.store');
        Route::get('/mutasi/history', [DevMutationController::class, 'history'])->name('mutasi.index.history');

        //activation Account
        Route::get('/activation-account', [DevActivationaccountController::class, 'index'])->name('activation-account.index');
        Route::get('/activation-account/approval', [DevActivationaccountController::class, 'approval'])->name('activation-account.approval');
        Route::get('/activation-account/approve{id}', [DevActivationaccountController::class, 'approve'])->name('activation-account.approve');

        //user
        Route::get('/user', [DevUserController::class, 'index'])->name('user.index');
        Route::get('/user/create', [DevUserController::class, 'create'])->name('user.create');
        Route::post('/user/store', [DevUserController::class, 'store'])->name('user.store');
        Route::post('/user/update', [DevUserController::class, 'update'])->name('user.update');
        Route::get('/user/delete{id}', [DevUserController::class, 'destroy'])->name('user.delete');
        Route::post('/user/profil', [DevUserController::class, 'profil'])->name('user.profil');
        Route::post('/user/password', [DevUserController::class, 'password'])->name('user.password');
        //member
        Route::get('/member', [DevMemberController::class, 'index'])->name('member.index');;
        Route::post('/member/store', [DevMemberController::class, 'store'])->name('member.store');
        Route::post('/member/update', [DevMemberController::class, 'update'])->name('member.update');
        Route::get('/member/delete{id}', [DevMemberController::class, 'destroy'])->name('member.delete');
        //akunMT5
        Route::get('/akunmt5', [DevAkunMT5Controller::class, 'index'])->name('akunmt5.index');
        Route::post('/akunmt5/store', [DevAkunMT5Controller::class, 'store'])->name('akunmt5.store');
        Route::post('/akunmt5/update', [DevAkunMT5Controller::class, 'update'])->name('akunmt5.update');
        //Bank
        Route::get('/bank', [DevBankController::class, 'index'])->name('bank.index');
        Route::post('/bank/store', [DevBankController::class, 'store'])->name('bank.store');
        Route::post('/bank/update', [DevBankController::class, 'update'])->name('bank.update');
        Route::get('/bank/delete{id}', [DevBankController::class, 'destroy'])->name('bank.delete');

        //level
        Route::get('/level', [DevLevelController::class, 'index'])->name('level.index');
        Route::post('/level/store', [DevLevelController::class, 'store'])->name('level.store');
        Route::post('/level/update', [DevLevelController::class, 'update'])->name('level.update');
        Route::get('/level/delete{id}', [DevLevelController::class, 'destroy'])->name('level.delete');
        //level
        Route::get('/robot', [DevRobotController::class, 'index'])->name('robot.index');
        Route::post('/robot/store', [DevRobotController::class, 'store'])->name('robot.store');
        Route::post('/robot/update', [DevRobotController::class, 'update'])->name('robot.update');
        Route::get('/robot/delete{id}', [DevRobotController::class, 'destroy'])->name('robot.delete');

        //Kurs
        Route::get('/kurs', [DevKursController::class, 'index'])->name('kurs.index');
        Route::post('/kurs/store', [DevKursController::class, 'store'])->name('kurs.store');
        Route::post('/kurs/update', [DevKursController::class, 'update'])->name('kurs.update');
        Route::get('/kurs/delete{id}', [DevKursController::class, 'destroy'])->name('kurs.delete');

        //Contact
        Route::post('/contact/update', [DevContactController::class, 'update'])->name('contact.update');
        Route::get('/contact', [DevContactController::class, 'index'])->name('contact.index');

        //Topup
        Route::get('/topup', [DevTopupController::class, 'index'])->name('topup.index');
        Route::get('/topup/approval', [DevTopupController::class, 'approval'])->name('topup.approval');
        Route::post('/topup/approve', [DevTopupController::class, 'approve'])->name('topup.approve');
        Route::get('/topupmt5/', [DevTopupController::class, 'indexmt5'])->name('topupmt5.index');
        Route::post('/topupmt5/tambah', [DevTopupController::class, 'tambah'])->name('topupmt5.tambah');
        Route::post('/topupmt5/tambahmodal', [DevTopupController::class, 'tambahmodal'])->name('topupmt5.tambahmodal');
        // Route::get('/topupmt5/kurang', [DevTopupController::class, 'tambah'])->name('topup.approve');
        // Route::post('/topupmt5/kurang{id}', [DevTopupController::class, 'approve'])->name('topup.approve');

        //WD
        Route::get('/withdraw', [DevWithdrawController::class, 'index'])->name('withdraw.index');
        Route::get('/withdraw/approval', [DevWithdrawController::class, 'approval'])->name('withdraw.approval');
        Route::post('/withdraw/approve', [DevWithdrawController::class, 'approve'])->name('withdraw.approve');

        //u=member bank
        Route::get('/member-bank', [DevMemberBankController::class, 'index'])->name('member-bank.index');
        Route::post('/member-bank/store', [DevMemberBankController::class, 'store'])->name('member-bank.store');
        Route::post('/member-bank/update', [DevMemberBankController::class, 'update'])->name('member-bank.update');
        Route::get('/member-bank/delete{id}', [DevMemberBankController::class, 'destroy'])->name('member-bank.delete');

        //version app
        Route::get('version-app', [DevVersionController::class, 'index'])->name('version.index');
        Route::post('version-app', [DevVersionController::class, 'store'])->name('version.store');

        //bypass robot
        Route::get('bypassrobot', [DevBypassController::class, 'index'])->name('bypassrobot.index');

        //networkt
        Route::get('network', [DevNetworkController::class, 'index'])->name('network.index');

        //keuntungan MT5

        Route::resources([

app/Http/Controllers/Dev/ActivationaccountController.php
<?php

namespace App\Http\Controllers\Dev;

use App\Http\Controllers\Controller;
use App\Models\Activationaccount;
use Illuminate\Http\Request;
use App\Jobs\ReferralJobs;
use Illuminate\Support\Facades\Http;
use DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Carbon;
use Illuminate\Support\Str;

use function App\Helper\levelcek;
use function App\Helper\ReferralHelper\bonuscek;
use function App\Helper\ReferralHelper\cek;
use Session;

class ActivationaccountController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $datas = DB::table('activation_accounts')
            ->select('activation_accounts.*', 'status.name as nama_status', 'users.name as nama_user', 'tabel_banks.bank_name as nama_bank')
            ->join('status', 'status.id', '=', 'activation_accounts.status')
            ->join('users', 'activation_accounts.user_id', '=', 'users.id')
            ->join('tabel_banks', 'tabel_banks.id', '=', 'activation_accounts.bank_id')
            ->where('activation_accounts.status', 5)
            ->where('activation_accounts.deleted_at', null)
            ->orderBy('activation_accounts.created_at', 'DESC')
            ->get();

        return view('page.dashboard.dev.activationaccount.index', compact('datas'));
    }

    public function approval()
    {
        $datas = DB::table('activation_accounts')
            ->select('activation_accounts.*', 'status.name as nama_status', 'users.name as nama_user', 'tabel_banks.bank_name as nama_bank', 'images.image_url as gambar')
            ->join('status', 'status.id', '=', 'activation_accounts.status')
            ->join('users', 'activation_accounts.user_id', '=', 'users.id')
            ->join('images', 'activation_accounts.image_id', '=', 'images.id')
            ->join('tabel_banks', 'tabel_banks.id', '=', 'activation_accounts.bank_id')
            ->where('activation_accounts.status', 4)
            ->where('activation_accounts.deleted_at', null)
            ->orderBy('activation_accounts.created_at', 'DESC')
            ->get();

        // dd($datas);

        return view('page.dashboard.dev.activationaccount.approval', compact('datas'));
    }

    public function approve($id)
    {

        DB::table('activation_accounts')->where('id', $id)->update([
            'status' => 5,
            'updated_at' => Carbon::now()
        ]);

        $getuserid = DB::select("select * from activation_accounts where id='$id'");
        foreach ($getuserid as $key) {
            $getrobot = DB::select("select * from users where id='$key->user_id'");
            foreach ($getrobot as $keyy) {
                DB::table('users')->where('id', $key->user_id)->update([
                    'status' => 2,
                ]);
            }
        }

        cek($getuserid[0]->user_id);
        levelcek($getuserid[0]->user_id);


        return redirect()->route('dashboard.dev.activation-account.approval')->with('berhasilapprove', '.');;
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Activationaccount::where('id', $id)->update([
            'status' => 5,
        ]);

        cek($id);

        return redirect()->route('dashboard.dev.activation-account.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Dev/AkunMT5Controller.php
<?php

namespace App\Http\Controllers\Dev;

use App\Http\Controllers\Controller;
use App\Models\Accountmt5;
use App\Models\User;
use Illuminate\Auth\Events\Validated;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Carbon;
use Session;

class AkunMT5Controller extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $datas = Accountmt5::with(['user'])->get();
        // dd($datas);
        // return json($datas);

        Session::put('menu','manajemenuser');
        Session::put('sub','akunmt5');
        return view('page.dashboard.dev.akunmt5.index', compact(['datas']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     *

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Accountmt5::create([
            'user_id' => $request->input('user_id'),
            'username' => $request->input('username'),
            'password' => $request->input('password'),
            'password_investor' => $request->input('passwordinv'),
            'server' => $request->input('server'),
            'ip_server' => $request->input('server_ip'),
            'created_at' => Carbon::now(),
        ]);
        return redirect()->route('dashboard.dev.akunmt5.index')->with('berhasil', '.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        Accountmt5::where('id', $request->input('id'))->update([
            'username' => $request->input('username'),
            'password' => $request->input('passwordedit'.$request->id),
            'password_investor' => $request->input('passwordinvedit'.$request->id),
            'server' => $request->input('server'),
            'ip_server' => $request->input('server_ip'),
            'updated_at' => Carbon::now(),
        ]);
        return redirect()->route('dashboard.dev.akunmt5.index')->with('berhasilupdate', '.');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/page/dashboard/dev/member-bank/index.blade.php
@extends('layouts.dash',['title'=>'Cipiti - Dashboard'])

@section('content')
<div class="container-fluid">

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="mt-0 header-title">Data Bank</h4>
                    <p class="text-muted font-14 mb-3">
                    </p>
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#standard-modal">Tambah Data</button>
                    <br><br>
                    <table id="datatable" class="table table-bordered dt-responsive table-responsive nowrap">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Bank</th>
                                <th>Kode</th>
                                <th>Member</th>
                                <th>Nama Akun</th>
                                <th>No. Rekening</th>
                                <th>Action</th>
                              </tr>
                        </thead>


                        <tbody>
                        @php
                            $i = 1 ;
                        @endphp
                        @foreach ($datas as $dt)
                        <tr>
                            <td>{{$i++}}</td>
                            <td>{{$dt->bank->nama_bank}}</td>
                            <td>{{$dt->bank->kode_bank}}</td>
                            <td>{{$dt->user->name}}</td>
                            <td>{{$dt->account_name}}</td>
                            <td>{{$dt->bank_rek}}</td>
                            <td><button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#modal-edit{{$dt->id}}"><i class="mdi mdi-pencil"></i>
                            </button>
                                <a href="/dashboard/dev/member-bank/delete{{$dt->id}}" class="btn btn-danger" onclick="return(confirm('Apakah Data ini Akan dihapus?'));"><i class="mdi mdi-trash-can"></i>
                                </a>
                            </td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div> <!-- end row -->


</div> <!-- container-fluid -->
@foreach ($datas as $dt)
<!-- Standard modal content -->
<div id="modal-edit{{$dt->id}}" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalupdate" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modalupdate">Update Data {{$dt->name}}</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">



                <form action="{{ route('dashboard.dev.member-bank.update') }}" class="parsley-examples" method="post">
                    @csrf
                    <input type="hidden" class="form-control" id="id" name="id" placeholder="Bank Persada" value="{{$dt->id}}">
                    <div class="mb-3">
                        <label for="bank" class="form-label">Bank</label>
                        <select class="form-select" id="bank_id" name="bank_id">
                            @foreach ($datab as $dts)
                            <option value="{{$dts->id}}">{{$dts->nama_bank}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="nama_akun" class="form-label">Nama Akun<span class="text-danger">*</span></label>
                        <input type="text" name="nama_akun" parsley-trigger="change" required placeholder="Enter Nama Akun" class="form-control" id="nama_akun" value="{{$dt->account_name}}"/>
                    </div>
                    <div class="mb-3">
                        <label for="no_rekening" class="form-label">No. Rekening<span class="text-danger">*</span></label>
                        <input type="number" name="no_rek" parsley-trigger="change" required placeholder="Enter Rekening" class="form-control" id="no_rek" value="{{$dt->bank_rek}}"/>
                    </div>



                    <div class="modal-footer">
                        <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </div>
        </form>
    </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
@endforeach

<div id="standard-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="standard-modalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="standard-modalLabel">Tambah Data</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">


                <form action="{{ route('dashboard.dev.member-bank.store') }}" class="parsley-examples" method="post">
                    @csrf
                    <div class="mb-3">
                        <label for="member" class="form-label">Member</label>
                        <select class="form-select" id="user_id" name="user_id">
                            @foreach ($data as $dta)
                            <option value="{{$dta->id}}">{{$dta->name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="bank" class="form-label">Bank</label>
                        <select class="form-select" id="bank_id" name="bank_id">
                            @foreach ($datab as $dts)
                            <option value="{{$dts->id}}">{{$dts->nama_bank}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="nama_akun" class="form-label">Nama Akun<span class="text-danger">*</span></label>
                        <input type="text" name="nama_akun" parsley-trigger="change" required placeholder="Enter Nama Akun" class="form-control" id="nama_akun" />
                    </div>
                    <div class="mb-3">
                        <label for="no_rekening" class="form-label">No. Rekening<span class="text-danger">*</span></label>
                        <input type="number" name="no_rek" parsley-trigger="change" required placeholder="Enter Rekening" class="form-control" id="no_rek" />
                    </div>




                    <div class="modal-footer">
                        <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </div>
        </form>
    </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
@endsection